import {Button} from 'antd';
import type {NextPage} from 'next';
import Head from 'next/head';
import {useOnMount} from '@baidu/bce-hooks';
import {setRem} from '@baidu/bce-helper';
import styles from '../styles/test_m.module.less';
import styles1 from '../styles/test1.module.scss';

const Test: NextPage = () => {
    useOnMount(() => {
        window.onresize = () => {
            setRem();
        };
        setRem();
    });
    return (
        <div>
            <Head>
                <title>testtest</title>
                <meta name="description" content="Generated by create next app" />
                {/* eslint-disable-next-line max-len */}
                <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no,shrink-to-fit=no" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            testtesttesttest
            <Button className={styles.test}>231</Button>
            <div className={styles.remrem}>remrem</div>
            <Button className={styles1.test}>888</Button>
        </div>
    );
};

export default Test;
