import {Button} from 'antd';
import type {NextPage} from 'next';
import Head from 'next/head';

const Test: NextPage = () => {
    return (
        <div>
            <Head>
                <title>testtest</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            testtesttesttest
            <Button>231</Button>
        </div>
    );
};

export default Test;
